settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations
  reminderCount: 1

  allmonitorsOperational: 'All Systems Up'
  notAllmonitorsOperational: 'Not All Systems Up'
  monitorLabelOperational: 'Up'
  monitorLabelNotOperational: 'Down'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'

monitors:
  - id: maxmeuk
    name: max.me.uk
    url: 'https://max.me.uk/'
  - id: notifi
    name: notifi.it
    url: 'https://notifi.it/'
  - id: transfermeit
    name: transferme.it
    url: 'https://transferme.it/'
  - id: idmyteam
    name: idmy.team
    url: 'https://idmy.team/'
  - id: cryptercouk
    name: crypter.co.uk
    url: 'https://crypter.co.uk/'
  - id: juliemitchellco
    name: juliemitchell.co
    url: 'https://juliemitchell.co/'
  - id: wickprojectscouk
    name: wickprojects.co.uk
    url: 'https://wickprojects.co.uk/'
  - id: taskermaritimecouk
    name: taskermaritime.co.uk
    url: 'https://taskermaritime.co.uk/'
  - id: mitchelldesignconsultancycom
    name: mitchelldesignconsultancy.com
    url: 'https://mitchelldesignconsultancy.com/'
